[package]
name = "accesskit_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.10.1", features = ["accesskit_unix"]}

[profile.dev]
opt-level = 3
